const db = require('../config/db')
const { DataTypes } = require('sequelize');

const Referral = db.define('referral', {
  /* 
    id, referrer_id and timestamps are...
    generated by sequelize 
  */
  }, {
    timestamps: true,
});

module.exports = Referral